openapi: 3.0.0
info:
  title: API Loja Virtual
  version: 0.0.1
tags:
  - produtos
paths:
  /produtos:
    get:
      tags:
        - produtos
      responses: 
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ArrayOfProdutos"
      security:
        -  JWTAuth: []
    post:
      tags:
        - produtos
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Produto'
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Produto'
        422:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
  /produtos/{id}:
    post:
      tags:
        - produtos
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Produto'
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Produto'
        422:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
    get:
      tags:
        - produtos
      parameters:
        - in: path
          type: string
          name: id
      responses: 
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ArrayOfProdutos"
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
    put:      
      tags:
        - produtos
      parameters:
        - in: path
          type: string
          name: id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Produto'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ArrayOfProdutos"
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
        422:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
    delete:
      tags:
        - produtos
      parameters:
        - in: path
          type: string
          name: id
      responses:
        204:
        404:

components:
  schemas:
    Produto:
      type: object
      properties:
        nome:
          type: string
        preco:
          type: number
    Mensagem:
      type: object
      properties:
        msg:
          type: string
    ArrayOfProdutos:
      type: array
      itens:
        $ref: '#/components/schemas/Produto'
  securityScheme
  
  s: 
    JWTAuth: 
      type: apiKey
      in: header
      name: Authorization